#!/usr/bin/env python3
"""
Watch content/incoming/ for new posts and hero images, validate, and publish.

Drop files into content/incoming/:
  - .md files with frontmatter (title, date, published, tags required)
  - .html files (auto-converted to markdown, frontmatter auto-generated)
  - .pdf files (auto-converted to markdown via pandoc, frontmatter auto-generated)
  - .webp/.png/.jpg hero images (named same as the post or referenced in frontmatter)

Usage:
  python3 scripts/publish_incoming.py              # Process all incoming files
  python3 scripts/publish_incoming.py --dry-run    # Validate without moving
  python3 scripts/publish_incoming.py --list       # Show what's waiting

Frontmatter example (for .md files):
  ---
  title: "My Post Title"
  date: "2026-07-24T10:00:00+00:00"
  published: true
  tags: "AI, LLM, Tools"
  hero: my-hero-image.webp   # optional: explicit hero filename
  ---
"""
from __future__ import annotations
import argparse, datetime as _dt, os, re, shutil, subprocess, sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INCOMING_DIR = os.path.join(PROJECT_ROOT, "content", "incoming")
POSTS_DIR = os.path.join(PROJECT_ROOT, "content", "posts")
HEROES_AUTO_DIR = os.path.join(PROJECT_ROOT, "public", "heroes", "auto")
HEROES_MANUAL_DIR = os.path.join(PROJECT_ROOT, "public", "heroes", "manual")

REQUIRED_FRONTMATTER = {"title", "date", "tags"}
IMAGE_EXTS = {".webp", ".png", ".jpg", ".jpeg"}
CONVERTIBLE_EXTS = {".html", ".htm", ".pdf"}
POST_EXTS = {".md"} | CONVERTIBLE_EXTS


def parse_frontmatter(content: str) -> tuple[dict[str, str], str]:
    """Parse YAML frontmatter from markdown content."""
    match = re.match(r"^---\n(.*?)\n---\n(.*)", content, re.DOTALL)
    if not match:
        return {}, content

    meta: dict[str, str] = {}
    for line in match.group(1).split("\n"):
        if ":" in line and not line.strip().startswith("-"):
            key, _, val = line.partition(":")
            meta[key.strip()] = val.strip().strip('"').strip("'")

    return meta, match.group(1), match.group(2)


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text.strip("-")[:60] or "post"


def _clean_title(title: str) -> str:
    """Strip URLs, localhost references, and Odysseus artifacts from a title."""
    # Remove URLs (http/https/localhost)
    title = re.sub(r"https?://[^\s]+", "", title)
    title = re.sub(r"localhost:\d+/[^\s]+", "", title)
    # Remove Odysseus research metadata that leaks into titles
    title = re.sub(r"\d+[\.\s]+\d+s?\s+Duration.*$", "", title, flags=re.IGNORECASE)
    # Collapse whitespace and strip
    title = re.sub(r"\s+", " ", title).strip()
    return title


def extract_title_from_html(html_content: str) -> str:
    """Extract title from HTML content."""
    # Try <title> tag
    match = re.search(r"<title[^>]*>(.*?)</title>", html_content, re.DOTALL | re.IGNORECASE)
    if match:
        return _clean_title(match.group(1))
    # Try first <h1> tag
    match = re.search(r"<h1[^>]*>(.*?)</h1>", html_content, re.DOTALL | re.IGNORECASE)
    if match:
        return _clean_title(re.sub(r"<[^>]+>", "", match.group(1)))
    return ""


def _clean_odysseus_artifacts(text: str) -> str:
    """Remove Odysseus UI artifacts that leak through HTML conversion."""
    lines = text.split("\n")
    cleaned = []
    skip_next_blank = False
    for line in lines:
        stripped = line.strip()
        # Skip Odysseus toolbar / metadata lines
        if stripped in ("Export ▾", "Save as PDF", "Download HTML"):
            continue
        if re.match(r"^\d+[\.\s]", stripped) and stripped.endswith(("s Duration", " Rounds", " Queries", " URLs Analyzed")):
            continue
        if re.match(r"^(openrouter/\S+|searxng|Searxng)\s+(Search|Model)$", stripped, re.IGNORECASE):
            continue
        if stripped.startswith("Generated by Odysseus"):
            continue
        if stripped == "Discuss":
            skip_next_blank = True
            continue
        if stripped == "Opens a new chat with this report as context.":
            continue
        if skip_next_blank and stripped == "":
            skip_next_blank = False
            continue
        skip_next_blank = False
        cleaned.append(line)
    return "\n".join(cleaned)


def convert_html_to_markdown(filepath: str) -> str | None:
    """Convert HTML file to markdown with frontmatter."""
    try:
        import markdownify
        with open(filepath, "r", encoding="utf-8") as f:
            html = f.read()

        title = extract_title_from_html(html)
        if not title:
            title = slugify(os.path.basename(filepath)).replace("-", " ").title()

        # Remove <style>, <script>, <nav>, <footer>, <header> blocks entirely (content + tags)
        html = re.sub(r"<(style|script|nav|footer|header)\b[^>]*>.*?</\1>", "", html, flags=re.DOTALL | re.IGNORECASE)
        body = markdownify.markdownify(html)
        body = _clean_odysseus_artifacts(body)
        # Clean URLs from the first heading (title line) — don't touch body links
        lines = body.split("\n")
        for i, line in enumerate(lines):
            if line.strip().startswith("#") or (i < 3 and line.strip()):
                lines[i] = _clean_title(line)
                break
        body = "\n".join(lines)
        body = re.sub(r"\n{3,}", "\n\n", body).strip()

        now = _dt.datetime.now(_dt.timezone.utc).isoformat()
        return (
            f'---\ntitle: "{title}"\ndate: "{now}"\npublished: true\n'
            f'source: publish_incoming.py (html conversion)\ntags: ""\n---\n\n{body}\n'
        )
    except ImportError:
        print("  ⚠️  markdownify not installed — run: pip install markdownify")
        return None
    except Exception as e:
        print(f"  ❌ HTML conversion failed: {e}")
        return None


def convert_pdf_to_markdown(filepath: str) -> str | None:
    """Convert PDF file to markdown with frontmatter via pdftotext."""
    try:
        result = subprocess.run(
            ["pdftotext", "-layout", filepath, "-"],
            capture_output=True, text=True, timeout=60
        )
        if result.returncode != 0:
            print(f"  ❌ pdftotext error: {result.stderr[:200]}")
            return None

        body = result.stdout.strip()
        if not body:
            print(f"  ❌ pdftotext produced empty output")
            return None

        # Clean up excessive whitespace but preserve paragraph breaks
        body = re.sub(r"[ \t]+", " ", body)
        body = re.sub(r"\n{3,}", "\n\n", body)

        # Try to extract title from first non-empty line
        lines = [l.strip() for l in body.split("\n") if l.strip()]
        title = _clean_title(lines[0]) if lines else ""
        # Truncate long titles
        if len(title) > 100:
            title = title[:97] + "..."
        if not title:
            title = slugify(os.path.basename(filepath)).replace("-", " ").title()

        now = _dt.datetime.now(_dt.timezone.utc).isoformat()
        return (
            f'---\ntitle: "{title}"\ndate: "{now}"\npublished: true\n'
            f'source: publish_incoming.py (pdf conversion)\ntags: ""\n---\n\n{body}\n'
        )
    except FileNotFoundError:
        print("  ⚠️  pdftotext not installed — run: brew install poppler")
        return None
    except Exception as e:
        print(f"  ❌ PDF conversion failed: {e}")
        return None


def convert_to_markdown(filepath: str) -> str | None:
    """Convert HTML or PDF to markdown. Returns None on failure."""
    ext = os.path.splitext(filepath)[1].lower()
    if ext in (".html", ".htm"):
        return convert_html_to_markdown(filepath)
    elif ext == ".pdf":
        return convert_pdf_to_markdown(filepath)
    return None


def validate_post(filepath: str, content: str | None = None) -> list[str]:
    """Validate a post file. Returns list of errors (empty = valid)."""
    errors = []
    filename = os.path.basename(filepath)

    if content is None:
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
        except Exception as e:
            errors.append(f"Cannot read file: {e}")
            return errors

    meta, _, body = parse_frontmatter(content)

    if not meta:
        errors.append("Missing frontmatter (file must start with --- delimited YAML)")
        return errors

    for field in REQUIRED_FRONTMATTER:
        if field not in meta:
            errors.append(f"Missing required frontmatter field: {field}")

    if meta.get("title", "").strip() == "":
        errors.append("Title is empty")

    if not body.strip():
        errors.append("Post body is empty")

    return errors


def find_hero_for_post(post_filename: str, meta: dict[str, str]) -> str | None:
    """Find a matching hero image for a post."""
    # Derive slug from filename, stripping convertible extensions
    slug = post_filename
    for ext in POST_EXTS:
        slug = slug.replace(ext, "")

    # Check explicit hero field in frontmatter
    hero_ref = meta.get("hero", "")
    if hero_ref:
        hero_path = os.path.join(INCOMING_DIR, hero_ref)
        if os.path.exists(hero_path):
            return hero_path

    # Look for image with same base name
    for ext in IMAGE_EXTS:
        candidate = os.path.join(INCOMING_DIR, slug + ext)
        if os.path.exists(candidate):
            return candidate

    # Look for any image that partially matches the slug (normalize separators)
    slug_norm = re.sub(r"[-_]+", " ", slug).lower()
    for fn in os.listdir(INCOMING_DIR):
        if os.path.splitext(fn)[1].lower() in IMAGE_EXTS:
            fn_norm = re.sub(r"[-_]+", " ", os.path.splitext(fn)[0]).lower()
            # Check if slug words appear in filename or vice versa
            slug_words = set(slug_norm.split())
            fn_words = set(fn_norm.split())
            if slug_words & fn_words and len(slug_words & fn_words) >= 2:
                return os.path.join(INCOMING_DIR, fn)

    return None


def check_duplicate_title(title: str) -> bool:
    """Check if a title already exists in published posts."""
    if not os.path.isdir(POSTS_DIR):
        return False
    for fn in os.listdir(POSTS_DIR):
        if not fn.endswith(".md"):
            continue
        with open(os.path.join(POSTS_DIR, fn), "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("title:"):
                    existing = line.split(":", 1)[1].strip().strip('"').strip("'")
                    if existing.lower() == title.lower():
                        return True
                    break
    return False


def process_post(filepath: str, dry_run: bool = False) -> bool:
    """Process a single incoming post. Returns True if successful."""
    filename = os.path.basename(filepath)
    ext = os.path.splitext(filename)[1].lower()

    # Convert non-markdown files
    content = None
    if ext in CONVERTIBLE_EXTS:
        print(f"  🔄 Converting {ext} → markdown: {filename}")
        content = convert_to_markdown(filepath)
        if not content:
            return False
        # Change filename to .md
        filename = os.path.splitext(filename)[0] + ".md"

    # Validate
    if ext == ".md" and content is None:
        errors = validate_post(filepath)
    else:
        errors = validate_post(filepath, content)
    if errors:
        print(f"  ❌ {filename}:")
        for e in errors:
            print(f"     - {e}")
        return False

    # Read content if not already converted
    if content is None:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

    meta, frontmatter_raw, body = parse_frontmatter(content)

    # Check for duplicate title
    title = meta.get("title", "")
    if check_duplicate_title(title):
        print(f"  ⚠️  Skipping {filename}: duplicate title '{title}'")
        return False

    # Find hero image (use original filename for matching)
    original_filename = os.path.basename(filepath)
    hero_path = find_hero_for_post(original_filename, meta)

    if dry_run:
        print(f"  ✅ {filename} → content/posts/{filename}")
        print(f"     Title: {title}")
        print(f"     Tags: {meta.get('tags', '(none)')}")
        if hero_path:
            slug = os.path.splitext(filename)[0]
            hero_ext = os.path.splitext(hero_path)[1]
            print(f"     Hero: {os.path.basename(hero_path)} → public/heroes/manual/{slug}{hero_ext}")
        else:
            print(f"     Hero: (none found — will use auto-generated)")
        return True

    # Write converted file or move original
    os.makedirs(POSTS_DIR, exist_ok=True)
    dest = os.path.join(POSTS_DIR, filename)
    if ext in CONVERTIBLE_EXTS:
        with open(dest, "w", encoding="utf-8") as f:
            f.write(content)
        os.remove(filepath)
        print(f"  📝 Converted & published: {filename}")
    else:
        shutil.move(filepath, dest)
        print(f"  📝 Published: {filename}")

    # Move hero image
    if hero_path:
        os.makedirs(HEROES_MANUAL_DIR, exist_ok=True)
        slug = os.path.splitext(filename)[0]
        hero_ext = os.path.splitext(hero_path)[1]
        hero_dest = os.path.join(HEROES_MANUAL_DIR, f"{slug}{hero_ext}")
        shutil.move(hero_path, hero_dest)
        print(f"  🖼️  Hero: {os.path.basename(hero_path)} → public/heroes/manual/{slug}{hero_ext}")

    return True


def list_incoming():
    """List files waiting in incoming/."""
    if not os.path.isdir(INCOMING_DIR):
        print("content/incoming/ does not exist yet.")
        return

    files = [f for f in os.listdir(INCOMING_DIR) if not f.startswith(".")]
    if not files:
        print("content/incoming/ is empty — nothing to publish.")
        return

    print(f"\nFiles in content/incoming/ ({len(files)}):\n")
    for fn in sorted(files):
        filepath = os.path.join(INCOMING_DIR, fn)
        ext = os.path.splitext(fn)[1].lower()

        if ext == ".md":
            errors = validate_post(filepath)
            status = "✅" if not errors else "❌"
            print(f"  {status} {fn}")
            if errors:
                for e in errors:
                    print(f"     - {e}")
        elif ext in CONVERTIBLE_EXTS:
            # Try conversion to validate
            content = convert_to_markdown(filepath)
            if content:
                errors = validate_post(filepath, content)
                status = "✅" if not errors else "⚠️"
                print(f"  {status} {fn} (will convert to .md)")
                if errors:
                    for e in errors:
                        print(f"     - {e}")
            else:
                print(f"  ❌ {fn} (conversion failed)")
        elif ext.lower() in IMAGE_EXTS:
            print(f"  🖼️  {fn}")
        else:
            print(f"  ⚠️  {fn} (unknown type)")
    print()


def main():
    parser = argparse.ArgumentParser(description="Publish incoming posts from content/incoming/")
    parser.add_argument("--dry-run", action="store_true", help="Validate without moving files")
    parser.add_argument("--list", action="store_true", help="List files waiting in incoming/")
    args = parser.parse_args()

    if args.list:
        list_incoming()
        return 0

    if not os.path.isdir(INCOMING_DIR):
        os.makedirs(INCOMING_DIR, exist_ok=True)
        print(f"Created {INCOMING_DIR} — drop .md/.html/.pdf files and hero images here.")
        return 0

    # Find post files (.md, .html, .pdf)
    post_files = sorted([
        os.path.join(INCOMING_DIR, f)
        for f in os.listdir(INCOMING_DIR)
        if os.path.splitext(f)[1].lower() in POST_EXTS and not f.startswith(".")
    ])

    if not post_files:
        print("No post files (.md/.html/.pdf) in content/incoming/ — nothing to publish.")
        return 0

    print(f"\n{'='*50}")
    print(f"  Publishing {len(post_files)} post(s) from content/incoming/")
    print(f"  Dry run: {args.dry_run}")
    print(f"{'='*50}\n")

    success = 0
    failed = 0

    for filepath in post_files:
        if process_post(filepath, dry_run=args.dry_run):
            success += 1
        else:
            failed += 1

    print(f"\n{'='*50}")
    print(f"  Done: {success} published, {failed} failed")
    print(f"{'='*50}\n")

    if not args.dry_run and success > 0:
        # Auto-commit and push
        try:
            subprocess.run(["git", "add", "content/posts/", "public/heroes/manual/"],
                         cwd=PROJECT_ROOT, check=True, capture_output=True)
            subprocess.run(["git", "commit", "-m", f"chore: publish {success} post(s) from incoming/"],
                         cwd=PROJECT_ROOT, check=True, capture_output=True)
            subprocess.run(["git", "push", "origin", "main"],
                         cwd=PROJECT_ROOT, check=True, capture_output=True)
            print("  🚀 Committed and pushed to main — Vercel will auto-deploy.")
        except subprocess.CalledProcessError as e:
            print(f"  ⚠️  Git error: {e}")

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
